name: Manh Duong
favicon: null
layout_spectrum: 0.7632625142578036
typography_spectrum: 0.7199208848178387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1812939967494458
  lightness: 0.8508660297375172
  saturation: 0.06641754857264459
  rhythmicContrast: 0.5387784885242581
purpose: []
